// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2rKIhpNBVVSEYLFwhxN9kDxsDlFkMMEM',
    appId: '1:383829373632:web:80aea5ca103f37b6dbb325',
    messagingSenderId: '383829373632',
    projectId: 'flutterfinalexam-8f6c8',
    authDomain: 'flutterfinalexam-8f6c8.firebaseapp.com',
    storageBucket: 'flutterfinalexam-8f6c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEa1kvMBmukcLdQEPfPmnH3xxFwUHrdjc',
    appId: '1:383829373632:android:219d380ceb3bb6b2dbb325',
    messagingSenderId: '383829373632',
    projectId: 'flutterfinalexam-8f6c8',
    storageBucket: 'flutterfinalexam-8f6c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKFaJKQjS4DAcwrx0Pmca6IA6hEZWN8g',
    appId: '1:383829373632:ios:bcd524fb0a6bde98dbb325',
    messagingSenderId: '383829373632',
    projectId: 'flutterfinalexam-8f6c8',
    storageBucket: 'flutterfinalexam-8f6c8.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKFaJKQjS4DAcwrx0Pmca6IA6hEZWN8g',
    appId: '1:383829373632:ios:bcd524fb0a6bde98dbb325',
    messagingSenderId: '383829373632',
    projectId: 'flutterfinalexam-8f6c8',
    storageBucket: 'flutterfinalexam-8f6c8.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2rKIhpNBVVSEYLFwhxN9kDxsDlFkMMEM',
    appId: '1:383829373632:web:a309cc08b918a551dbb325',
    messagingSenderId: '383829373632',
    projectId: 'flutterfinalexam-8f6c8',
    authDomain: 'flutterfinalexam-8f6c8.firebaseapp.com',
    storageBucket: 'flutterfinalexam-8f6c8.firebasestorage.app',
  );
}
